# Rwanda administrative divisions
# Used in both frontend and backend validation

RWANDA_LOCATIONS = {
    "Kigali City": {
        "Gasabo": {
            "Bumbogo":    ["Cyabagarura", "Gahanga", "Kabuga", "Nyamugari", "Nyarutovu"],
            "Gatsata":    ["Cyaruzinge", "Gatoki", "Kibagabaga", "Kivugiza", "Nyagasambu"],
            "Gikomero":   ["Gikomero", "Kabuga", "Murama", "Ruturusu", "Shyogwe"],
            "Gisozi":     ["Cyibuje", "Gasanze", "Karuruma", "Kibaza", "Rubirizi"],
            "Jabana":     ["Gahanga", "Giticyinyoni", "Kabeza", "Ruturusu", "Shyorongi"],
            "Jali":       ["Bwiza", "Gahombo", "Jali", "Kagugu", "Nyagasambu"],
            "Kagugu":     ["Gahombo", "Kagugu", "Kibagabaga", "Nyarutovu", "Rubirizi"],
            "Kacyiru":    ["Kamatamu", "Kibaza", "Kicukiro", "Nyarutovu", "Rusororo"],
            "Kimironko":  ["Bibare", "Kibagabaga", "Kimironko", "Nduba", "Nyarutovu"],
            "Kinyinya":   ["Bwiza", "Kinyinya", "Nduba", "Rusororo", "Shyorongi"],
            "Ndera":      ["Cyabagarura", "Murama", "Ndera", "Ruturusu", "Shyorongi"],
            "Nduba":      ["Cyibuje", "Gahombo", "Gasanze", "Nduba", "Rusororo"],
            "Remera":     ["Kibagabaga", "Kimironko", "Nyarutovu", "Remera", "Rubirizi"],
            "Rusororo":   ["Bwiza", "Gahombo", "Rusororo", "Shyorongi", "Murama"],
            "Ruturusu":   ["Cyabagarura", "Kabuga", "Ruturusu", "Shyogwe", "Murama"],
        },
        "Kicukiro": {
            "Gahanga":    ["Gahanga", "Gako", "Kabeza", "Karuruma", "Kigarama"],
            "Gatenga":    ["Gatenga", "Kibaza", "Kigarama", "Kinyinya", "Nyarugunga"],
            "Gikondo":    ["Gikondo", "Kabeza", "Kigarama", "Nyarugunga", "Rugunga"],
            "Kagarama":   ["Kagarama", "Kibaza", "Kicukiro", "Nyarugunga", "Rugunga"],
            "Kanombe":    ["Kabeza", "Kanombe", "Kigarama", "Nyarugunga", "Rugunga"],
            "Kicukiro":   ["Gikondo", "Kicukiro", "Nyarugunga", "Rugunga", "Kagarama"],
            "Kigarama":   ["Gahanga", "Kigarama", "Kinyinya", "Nyarugunga", "Rugunga"],
            "Masaka":     ["Gako", "Kabeza", "Masaka", "Nyarugunga", "Rugunga"],
            "Niboye":     ["Kibaza", "Kicukiro", "Niboye", "Nyarugunga", "Rugunga"],
            "Nyarugunga": ["Gikondo", "Kigarama", "Nyarugunga", "Rugunga", "Kagarama"],
        },
        "Nyarugenge": {
            "Gitega":     ["Biryogo", "Gatare", "Gitega", "Kimisagara", "Mageragere"],
            "Kanyinya":   ["Biryogo", "Gatare", "Kanyinya", "Kimisagara", "Nyakabanda"],
            "Kigali":     ["Biryogo", "Gitega", "Kigali", "Kimisagara", "Nyakabanda"],
            "Kimisagara": ["Biryogo", "Gitega", "Kimisagara", "Mageragere", "Nyakabanda"],
            "Mageragere": ["Biryogo", "Gitega", "Kimisagara", "Mageragere", "Nyakabanda"],
            "Muhima":     ["Biryogo", "Gatare", "Kimisagara", "Muhima", "Nyakabanda"],
            "Nyakabanda": ["Biryogo", "Gatare", "Kimisagara", "Muhima", "Nyakabanda"],
            "Nyamirambo": ["Biryogo", "Gatare", "Kimisagara", "Nyamirambo", "Nyakabanda"],
            "Nyarugenge": ["Biryogo", "Gitega", "Kimisagara", "Nyakabanda", "Nyarugenge"],
            "Rwezamenyo": ["Biryogo", "Kimisagara", "Muhima", "Nyakabanda", "Rwezamenyo"],
        },
    },
    "Northern": {
        "Burera":  {"Bungwe": ["Bungwe", "Cyungo", "Gatebe", "Kagogo", "Nyamiyaga"], "Butaro": ["Butaro", "Cyungo", "Gitwa", "Kagogo", "Rusarabuye"], "Cyanika": ["Cyanika", "Gatebe", "Gitwa", "Kagogo", "Nyamiyaga"], "Gahunga": ["Bungwe", "Gahunga", "Gitwa", "Kagogo", "Rusarabuye"], "Gatebe": ["Bungwe", "Cyanika", "Gatebe", "Nyamiyaga", "Rusarabuye"], "Gitwa": ["Bungwe", "Butaro", "Gitwa", "Kagogo", "Nyamiyaga"], "Kagogo": ["Bungwe", "Butaro", "Cyanika", "Kagogo", "Nyamiyaga"], "Kinoni": ["Bungwe", "Butaro", "Gitwa", "Kinoni", "Nyamiyaga"], "Kinyababa": ["Bungwe", "Cyanika", "Gitwa", "Kinyababa", "Nyamiyaga"], "Kivuye": ["Bungwe", "Cyanika", "Gitwa", "Kivuye", "Nyamiyaga"], "Nemba": ["Bungwe", "Cyanika", "Gitwa", "Nemba", "Nyamiyaga"], "Rugarama": ["Bungwe", "Cyanika", "Gitwa", "Nyamiyaga", "Rugarama"], "Rugendabari": ["Bungwe", "Cyanika", "Gitwa", "Nyamiyaga", "Rugendabari"], "Ruhunde": ["Bungwe", "Cyanika", "Gitwa", "Nyamiyaga", "Ruhunde"], "Rusarabuye": ["Bungwe", "Cyanika", "Gitwa", "Nyamiyaga", "Rusarabuye"], "Rwerere": ["Bungwe", "Cyanika", "Gitwa", "Nyamiyaga", "Rwerere"]},
        "Gakenke": {"Busengo": ["Busengo", "Cyabingo", "Gaseke", "Kivuruga", "Muzo"], "Coko": ["Busengo", "Coko", "Gaseke", "Kivuruga", "Muzo"], "Cyabingo": ["Busengo", "Cyabingo", "Gaseke", "Kivuruga", "Muzo"], "Gaseke": ["Busengo", "Cyabingo", "Gaseke", "Kivuruga", "Muzo"], "Janja": ["Busengo", "Cyabingo", "Gaseke", "Janja", "Muzo"], "Kamubuga": ["Busengo", "Cyabingo", "Gaseke", "Kamubuga", "Muzo"], "Karambo": ["Busengo", "Cyabingo", "Gaseke", "Karambo", "Muzo"], "Kivuruga": ["Busengo", "Cyabingo", "Gaseke", "Kivuruga", "Muzo"], "Mataba": ["Busengo", "Cyabingo", "Gaseke", "Mataba", "Muzo"], "Minazi": ["Busengo", "Cyabingo", "Gaseke", "Minazi", "Muzo"], "Mugunga": ["Busengo", "Cyabingo", "Gaseke", "Mugunga", "Muzo"], "Muhondo": ["Busengo", "Cyabingo", "Gaseke", "Muhondo", "Muzo"], "Muzo": ["Busengo", "Cyabingo", "Gaseke", "Kivuruga", "Muzo"], "Nemba": ["Busengo", "Cyabingo", "Gaseke", "Muzo", "Nemba"], "Ruli": ["Busengo", "Cyabingo", "Gaseke", "Muzo", "Ruli"], "Rusasa": ["Busengo", "Cyabingo", "Gaseke", "Muzo", "Rusasa"], "Rushashi": ["Busengo", "Cyabingo", "Gaseke", "Muzo", "Rushashi"]},
        "Gicumbi": {"Bukure": ["Bukure", "Cyumba", "Gaseke", "Kaniga", "Rushaki"], "Bungwe": ["Bungwe", "Cyumba", "Gaseke", "Kaniga", "Rushaki"], "Byumba": ["Byumba", "Cyumba", "Gaseke", "Kaniga", "Rushaki"], "Cyumba": ["Bukure", "Cyumba", "Gaseke", "Kaniga", "Rushaki"], "Giti": ["Bukure", "Cyumba", "Gaseke", "Giti", "Rushaki"], "Kaniga": ["Bukure", "Cyumba", "Gaseke", "Kaniga", "Rushaki"], "Manyagiro": ["Bukure", "Cyumba", "Gaseke", "Manyagiro", "Rushaki"], "Miyove": ["Bukure", "Cyumba", "Gaseke", "Miyove", "Rushaki"], "Muguna": ["Bukure", "Cyumba", "Gaseke", "Muguna", "Rushaki"], "Mukarange": ["Bukure", "Cyumba", "Gaseke", "Mukarange", "Rushaki"], "Muko": ["Bukure", "Cyumba", "Gaseke", "Muko", "Rushaki"], "Mutete": ["Bukure", "Cyumba", "Gaseke", "Mutete", "Rushaki"], "Nyamiyaga": ["Bukure", "Cyumba", "Gaseke", "Nyamiyaga", "Rushaki"], "Nyamirama": ["Bukure", "Cyumba", "Gaseke", "Nyamirama", "Rushaki"], "Rushaki": ["Bukure", "Cyumba", "Gaseke", "Kaniga", "Rushaki"], "Rutare": ["Bukure", "Cyumba", "Gaseke", "Rutare", "Rushaki"], "Ruvune": ["Bukure", "Cyumba", "Gaseke", "Ruvune", "Rushaki"], "Rwamiko": ["Bukure", "Cyumba", "Gaseke", "Rwamiko", "Rushaki"], "Shangasha": ["Bukure", "Cyumba", "Gaseke", "Rushaki", "Shangasha"]},
        "Musanze": {"Busogo": ["Busogo", "Cyuve", "Gataraga", "Kinigi", "Muhoza"], "Cyuve": ["Busogo", "Cyuve", "Gataraga", "Kinigi", "Muhoza"], "Gataraga": ["Busogo", "Cyuve", "Gataraga", "Kinigi", "Muhoza"], "Gashaki": ["Busogo", "Cyuve", "Gashaki", "Kinigi", "Muhoza"], "Ingenzi": ["Busogo", "Cyuve", "Gataraga", "Ingenzi", "Muhoza"], "Kinigi": ["Busogo", "Cyuve", "Gataraga", "Kinigi", "Muhoza"], "Muhoza": ["Busogo", "Cyuve", "Gataraga", "Kinigi", "Muhoza"], "Musanze": ["Busogo", "Cyuve", "Gataraga", "Musanze", "Muhoza"], "Nkotsi": ["Busogo", "Cyuve", "Gataraga", "Nkotsi", "Muhoza"], "Nyange": ["Busogo", "Cyuve", "Gataraga", "Nyange", "Muhoza"], "Remera": ["Busogo", "Cyuve", "Gataraga", "Remera", "Muhoza"], "Rwaza": ["Busogo", "Cyuve", "Gataraga", "Rwaza", "Muhoza"], "Shingiro": ["Busogo", "Cyuve", "Gataraga", "Shingiro", "Muhoza"]},
        "Rulindo": {"Base": ["Base", "Burega", "Bushoki", "Buyoga", "Cyinzuzi"], "Burega": ["Base", "Burega", "Bushoki", "Buyoga", "Cyinzuzi"], "Bushoki": ["Base", "Burega", "Bushoki", "Buyoga", "Cyinzuzi"], "Buyoga": ["Base", "Burega", "Bushoki", "Buyoga", "Cyinzuzi"], "Cyinzuzi": ["Base", "Burega", "Bushoki", "Buyoga", "Cyinzuzi"], "Cyungo": ["Base", "Burega", "Bushoki", "Cyungo", "Cyinzuzi"], "Kinihira": ["Base", "Burega", "Bushoki", "Kinihira", "Cyinzuzi"], "Kisaro": ["Base", "Burega", "Bushoki", "Kisaro", "Cyinzuzi"], "Masoro": ["Base", "Burega", "Bushoki", "Masoro", "Cyinzuzi"], "Mbogo": ["Base", "Burega", "Bushoki", "Mbogo", "Cyinzuzi"], "Murambi": ["Base", "Burega", "Bushoki", "Murambi", "Cyinzuzi"], "Ngoma": ["Base", "Burega", "Bushoki", "Ngoma", "Cyinzuzi"], "Ntarabana": ["Base", "Burega", "Bushoki", "Ntarabana", "Cyinzuzi"], "Rukozo": ["Base", "Burega", "Bushoki", "Rukozo", "Cyinzuzi"], "Rusiga": ["Base", "Burega", "Bushoki", "Rusiga", "Cyinzuzi"], "Shyorongi": ["Base", "Burega", "Bushoki", "Shyorongi", "Cyinzuzi"], "Tumba": ["Base", "Burega", "Bushoki", "Tumba", "Cyinzuzi"]},
    },
    "Southern": {
        "Gisagara": {"Gikonko": ["Gikonko", "Gishubi", "Kansi", "Muganza", "Save"], "Gishubi": ["Gikonko", "Gishubi", "Kansi", "Muganza", "Save"], "Kansi": ["Gikonko", "Gishubi", "Kansi", "Muganza", "Save"], "Kigembe": ["Gikonko", "Gishubi", "Kansi", "Kigembe", "Save"], "Mamba": ["Gikonko", "Gishubi", "Kansi", "Mamba", "Save"], "Muganza": ["Gikonko", "Gishubi", "Kansi", "Muganza", "Save"], "Mugombwa": ["Gikonko", "Gishubi", "Kansi", "Mugombwa", "Save"], "Mukindo": ["Gikonko", "Gishubi", "Kansi", "Mukindo", "Save"], "Musha": ["Gikonko", "Gishubi", "Kansi", "Musha", "Save"], "Ndora": ["Gikonko", "Gishubi", "Kansi", "Ndora", "Save"], "Nyanza": ["Gikonko", "Gishubi", "Kansi", "Nyanza", "Save"], "Save": ["Gikonko", "Gishubi", "Kansi", "Muganza", "Save"]},
        "Huye":    {"Gishamvu": ["Cyarwa", "Gishamvu", "Huye", "Karama", "Mbazi"], "Huye": ["Cyarwa", "Gishamvu", "Huye", "Karama", "Mbazi"], "Karama": ["Cyarwa", "Gishamvu", "Huye", "Karama", "Mbazi"], "Kigoma": ["Cyarwa", "Gishamvu", "Kigoma", "Karama", "Mbazi"], "Kinazi": ["Cyarwa", "Gishamvu", "Kinazi", "Karama", "Mbazi"], "Maraba": ["Cyarwa", "Gishamvu", "Maraba", "Karama", "Mbazi"], "Mbazi": ["Cyarwa", "Gishamvu", "Huye", "Karama", "Mbazi"], "Mukura": ["Cyarwa", "Gishamvu", "Mukura", "Karama", "Mbazi"], "Ngoma": ["Cyarwa", "Gishamvu", "Ngoma", "Karama", "Mbazi"], "Ruhashya": ["Cyarwa", "Gishamvu", "Ruhashya", "Karama", "Mbazi"], "Rusatira": ["Cyarwa", "Gishamvu", "Rusatira", "Karama", "Mbazi"], "Rwaniro": ["Cyarwa", "Gishamvu", "Rwaniro", "Karama", "Mbazi"], "Simbi": ["Cyarwa", "Gishamvu", "Simbi", "Karama", "Mbazi"], "Tumba": ["Cyarwa", "Gishamvu", "Tumba", "Karama", "Mbazi"]},
        "Kamonyi": {"Gacurabwenge": ["Gacurabwenge", "Kamonyi", "Mugina", "Musambira", "Rukoma"], "Kamonyi": ["Gacurabwenge", "Kamonyi", "Mugina", "Musambira", "Rukoma"], "Kayenzi": ["Gacurabwenge", "Kayenzi", "Mugina", "Musambira", "Rukoma"], "Kayumba": ["Gacurabwenge", "Kayumba", "Mugina", "Musambira", "Rukoma"], "Mugina": ["Gacurabwenge", "Kamonyi", "Mugina", "Musambira", "Rukoma"], "Musambira": ["Gacurabwenge", "Kamonyi", "Mugina", "Musambira", "Rukoma"], "Ngamba": ["Gacurabwenge", "Kamonyi", "Mugina", "Ngamba", "Rukoma"], "Rukoma": ["Gacurabwenge", "Kamonyi", "Mugina", "Musambira", "Rukoma"], "Runda": ["Gacurabwenge", "Kamonyi", "Mugina", "Runda", "Rukoma"], "Rugarika": ["Gacurabwenge", "Kamonyi", "Mugina", "Rugarika", "Rukoma"]},
        "Muhanga": {"Cyeza": ["Cyeza", "Kabacuzi", "Kibangu", "Kiyumba", "Muhanga"], "Kabacuzi": ["Cyeza", "Kabacuzi", "Kibangu", "Kiyumba", "Muhanga"], "Kibangu": ["Cyeza", "Kabacuzi", "Kibangu", "Kiyumba", "Muhanga"], "Kiyumba": ["Cyeza", "Kabacuzi", "Kibangu", "Kiyumba", "Muhanga"], "Muhanga": ["Cyeza", "Kabacuzi", "Kibangu", "Kiyumba", "Muhanga"], "Mushishiro": ["Cyeza", "Kabacuzi", "Kibangu", "Mushishiro", "Muhanga"], "Nyabinoni": ["Cyeza", "Kabacuzi", "Kibangu", "Nyabinoni", "Muhanga"], "Nyamabuye": ["Cyeza", "Kabacuzi", "Kibangu", "Nyamabuye", "Muhanga"], "Nyamiyaga": ["Cyeza", "Kabacuzi", "Kibangu", "Nyamiyaga", "Muhanga"], "Rongi": ["Cyeza", "Kabacuzi", "Kibangu", "Rongi", "Muhanga"], "Rugendabari": ["Cyeza", "Kabacuzi", "Kibangu", "Rugendabari", "Muhanga"]},
        "Nyamagabe": {"Buruhukiro": ["Buruhukiro", "Cyanika", "Gasaka", "Gatare", "Kaduha"], "Cyanika": ["Buruhukiro", "Cyanika", "Gasaka", "Gatare", "Kaduha"], "Gasaka": ["Buruhukiro", "Cyanika", "Gasaka", "Gatare", "Kaduha"], "Gatare": ["Buruhukiro", "Cyanika", "Gasaka", "Gatare", "Kaduha"], "Kaduha": ["Buruhukiro", "Cyanika", "Gasaka", "Gatare", "Kaduha"], "Kamegeri": ["Buruhukiro", "Cyanika", "Gasaka", "Kamegeri", "Kaduha"], "Kibirizi": ["Buruhukiro", "Cyanika", "Gasaka", "Kibirizi", "Kaduha"], "Kibumbwe": ["Buruhukiro", "Cyanika", "Gasaka", "Kibumbwe", "Kaduha"], "Kitabi": ["Buruhukiro", "Cyanika", "Gasaka", "Kitabi", "Kaduha"], "Mbazi": ["Buruhukiro", "Cyanika", "Gasaka", "Mbazi", "Kaduha"], "Mugano": ["Buruhukiro", "Cyanika", "Gasaka", "Mugano", "Kaduha"], "Musange": ["Buruhukiro", "Cyanika", "Gasaka", "Musange", "Kaduha"], "Musebeya": ["Buruhukiro", "Cyanika", "Gasaka", "Musebeya", "Kaduha"], "Mushubi": ["Buruhukiro", "Cyanika", "Gasaka", "Mushubi", "Kaduha"], "Nkomane": ["Buruhukiro", "Cyanika", "Gasaka", "Nkomane", "Kaduha"], "Tare": ["Buruhukiro", "Cyanika", "Gasaka", "Tare", "Kaduha"], "Uwinkingi": ["Buruhukiro", "Cyanika", "Gasaka", "Uwinkingi", "Kaduha"]},
        "Nyanza":   {"Busasamana": ["Busasamana", "Cyabakamyi", "Kigoma", "Muyira", "Nyagisozi"], "Cyabakamyi": ["Busasamana", "Cyabakamyi", "Kigoma", "Muyira", "Nyagisozi"], "Kigoma": ["Busasamana", "Cyabakamyi", "Kigoma", "Muyira", "Nyagisozi"], "Muyira": ["Busasamana", "Cyabakamyi", "Kigoma", "Muyira", "Nyagisozi"], "Ntyazo": ["Busasamana", "Cyabakamyi", "Kigoma", "Ntyazo", "Nyagisozi"], "Nyagisozi": ["Busasamana", "Cyabakamyi", "Kigoma", "Muyira", "Nyagisozi"], "Nyamirongo": ["Busasamana", "Cyabakamyi", "Kigoma", "Nyamirongo", "Nyagisozi"], "Nyanza": ["Busasamana", "Cyabakamyi", "Kigoma", "Nyanza", "Nyagisozi"], "Rwabicuma": ["Busasamana", "Cyabakamyi", "Kigoma", "Rwabicuma", "Nyagisozi"], "Vumbi": ["Busasamana", "Cyabakamyi", "Kigoma", "Vumbi", "Nyagisozi"]},
        "Nyaruguru": {"Cyahinda": ["Cyahinda", "Kibeho", "Mata", "Munini", "Ngera"], "Kibeho": ["Cyahinda", "Kibeho", "Mata", "Munini", "Ngera"], "Kivu": ["Cyahinda", "Kibeho", "Kivu", "Munini", "Ngera"], "Mata": ["Cyahinda", "Kibeho", "Mata", "Munini", "Ngera"], "Munini": ["Cyahinda", "Kibeho", "Mata", "Munini", "Ngera"], "Ngera": ["Cyahinda", "Kibeho", "Mata", "Munini", "Ngera"], "Ngoma": ["Cyahinda", "Kibeho", "Mata", "Ngoma", "Ngera"], "Nyabimata": ["Cyahinda", "Kibeho", "Mata", "Nyabimata", "Ngera"], "Nyagisozi": ["Cyahinda", "Kibeho", "Mata", "Nyagisozi", "Ngera"], "Ruheru": ["Cyahinda", "Kibeho", "Mata", "Ruheru", "Ngera"], "Ruramba": ["Cyahinda", "Kibeho", "Mata", "Ruramba", "Ngera"], "Rusenge": ["Cyahinda", "Kibeho", "Mata", "Rusenge", "Ngera"], "Simbi": ["Cyahinda", "Kibeho", "Mata", "Simbi", "Ngera"], "Uwinkingi": ["Cyahinda", "Kibeho", "Mata", "Uwinkingi", "Ngera"]},
        "Ruhango":  {"Bweramana": ["Bweramana", "Byimana", "Kabagari", "Kinazi", "Mbuye"], "Byimana": ["Bweramana", "Byimana", "Kabagari", "Kinazi", "Mbuye"], "Kabagari": ["Bweramana", "Byimana", "Kabagari", "Kinazi", "Mbuye"], "Kinazi": ["Bweramana", "Byimana", "Kabagari", "Kinazi", "Mbuye"], "Mbuye": ["Bweramana", "Byimana", "Kabagari", "Kinazi", "Mbuye"], "Mbogo": ["Bweramana", "Byimana", "Kabagari", "Mbogo", "Mbuye"], "Mpanga": ["Bweramana", "Byimana", "Kabagari", "Mpanga", "Mbuye"], "Mwendo": ["Bweramana", "Byimana", "Kabagari", "Mwendo", "Mbuye"], "Ntongwe": ["Bweramana", "Byimana", "Kabagari", "Ntongwe", "Mbuye"], "Ruhango": ["Bweramana", "Byimana", "Kabagari", "Kinazi", "Ruhango"]},
    },
    "Eastern": {
        "Bugesera": {"Gashora": ["Gashora", "Juru", "Kamabuye", "Mareba", "Mayange"], "Juru": ["Gashora", "Juru", "Kamabuye", "Mareba", "Mayange"], "Kamabuye": ["Gashora", "Juru", "Kamabuye", "Mareba", "Mayange"], "Mareba": ["Gashora", "Juru", "Kamabuye", "Mareba", "Mayange"], "Mayange": ["Gashora", "Juru", "Kamabuye", "Mareba", "Mayange"], "Mwogo": ["Gashora", "Juru", "Kamabuye", "Mwogo", "Mayange"], "Ngeruka": ["Gashora", "Juru", "Kamabuye", "Ngeruka", "Mayange"], "Ntarama": ["Gashora", "Juru", "Kamabuye", "Ntarama", "Mayange"], "Nyamata": ["Gashora", "Juru", "Kamabuye", "Nyamata", "Mayange"], "Nyarugenge": ["Gashora", "Juru", "Kamabuye", "Nyarugenge", "Mayange"], "Rilima": ["Gashora", "Juru", "Kamabuye", "Rilima", "Mayange"], "Ruhuha": ["Gashora", "Juru", "Kamabuye", "Ruhuha", "Mayange"], "Rweru": ["Gashora", "Juru", "Kamabuye", "Rweru", "Mayange"], "Shyara": ["Gashora", "Juru", "Kamabuye", "Shyara", "Mayange"]},
        "Gatsibo": {"Gasange": ["Gasange", "Gitoki", "Kageyo", "Kiramuruzi", "Kiziguro"], "Gitoki": ["Gasange", "Gitoki", "Kageyo", "Kiramuruzi", "Kiziguro"], "Kageyo": ["Gasange", "Gitoki", "Kageyo", "Kiramuruzi", "Kiziguro"], "Kiramuruzi": ["Gasange", "Gitoki", "Kageyo", "Kiramuruzi", "Kiziguro"], "Kiziguro": ["Gasange", "Gitoki", "Kageyo", "Kiramuruzi", "Kiziguro"], "Muhura": ["Gasange", "Gitoki", "Kageyo", "Muhura", "Kiziguro"], "Murambi": ["Gasange", "Gitoki", "Kageyo", "Murambi", "Kiziguro"], "Ngarama": ["Gasange", "Gitoki", "Kageyo", "Ngarama", "Kiziguro"], "Nyagihanga": ["Gasange", "Gitoki", "Kageyo", "Nyagihanga", "Kiziguro"], "Remera": ["Gasange", "Gitoki", "Kageyo", "Remera", "Kiziguro"], "Rugarama": ["Gasange", "Gitoki", "Kageyo", "Rugarama", "Kiziguro"], "Rwimbogo": ["Gasange", "Gitoki", "Kageyo", "Rwimbogo", "Kiziguro"]},
        "Kayonza": {"Gahini": ["Gahini", "Kabare", "Kanage", "Kayonza", "Mukarange"], "Kabare": ["Gahini", "Kabare", "Kanage", "Kayonza", "Mukarange"], "Kanage": ["Gahini", "Kabare", "Kanage", "Kayonza", "Mukarange"], "Kayonza": ["Gahini", "Kabare", "Kanage", "Kayonza", "Mukarange"], "Mukarange": ["Gahini", "Kabare", "Kanage", "Kayonza", "Mukarange"], "Murundi": ["Gahini", "Kabare", "Kanage", "Murundi", "Mukarange"], "Mwiri": ["Gahini", "Kabare", "Kanage", "Mwiri", "Mukarange"], "Ndego": ["Gahini", "Kabare", "Kanage", "Ndego", "Mukarange"], "Nyamirama": ["Gahini", "Kabare", "Kanage", "Nyamirama", "Mukarange"], "Rukara": ["Gahini", "Kabare", "Kanage", "Rukara", "Mukarange"], "Ruramira": ["Gahini", "Kabare", "Kanage", "Ruramira", "Mukarange"], "Rwinkwavu": ["Gahini", "Kabare", "Kanage", "Rwinkwavu", "Mukarange"]},
        "Kirehe":   {"Gahara": ["Gahara", "Gatore", "Kigarama", "Kigina", "Kirehe"], "Gatore": ["Gahara", "Gatore", "Kigarama", "Kigina", "Kirehe"], "Kigarama": ["Gahara", "Gatore", "Kigarama", "Kigina", "Kirehe"], "Kigina": ["Gahara", "Gatore", "Kigarama", "Kigina", "Kirehe"], "Kirehe": ["Gahara", "Gatore", "Kigarama", "Kigina", "Kirehe"], "Mahama": ["Gahara", "Gatore", "Kigarama", "Mahama", "Kirehe"], "Mpanga": ["Gahara", "Gatore", "Kigarama", "Mpanga", "Kirehe"], "Musaza": ["Gahara", "Gatore", "Kigarama", "Musaza", "Kirehe"], "Mushikiri": ["Gahara", "Gatore", "Kigarama", "Mushikiri", "Kirehe"], "Nasho": ["Gahara", "Gatore", "Kigarama", "Nasho", "Kirehe"], "Nyamugari": ["Gahara", "Gatore", "Kigarama", "Nyamugari", "Kirehe"], "Nyarubuye": ["Gahara", "Gatore", "Kigarama", "Nyarubuye", "Kirehe"]},
        "Ngoma":    {"Gashanda": ["Gashanda", "Jarama", "Karembo", "Kazo", "Kibungo"], "Jarama": ["Gashanda", "Jarama", "Karembo", "Kazo", "Kibungo"], "Karembo": ["Gashanda", "Jarama", "Karembo", "Kazo", "Kibungo"], "Kazo": ["Gashanda", "Jarama", "Karembo", "Kazo", "Kibungo"], "Kibungo": ["Gashanda", "Jarama", "Karembo", "Kazo", "Kibungo"], "Mugesera": ["Gashanda", "Jarama", "Karembo", "Mugesera", "Kibungo"], "Murama": ["Gashanda", "Jarama", "Karembo", "Murama", "Kibungo"], "Mutenderi": ["Gashanda", "Jarama", "Karembo", "Mutenderi", "Kibungo"], "Remera": ["Gashanda", "Jarama", "Karembo", "Remera", "Kibungo"], "Rukira": ["Gashanda", "Jarama", "Karembo", "Rukira", "Kibungo"], "Rukumberi": ["Gashanda", "Jarama", "Karembo", "Rukumberi", "Kibungo"], "Rurenge": ["Gashanda", "Jarama", "Karembo", "Rurenge", "Kibungo"], "Sake": ["Gashanda", "Jarama", "Karembo", "Sake", "Kibungo"], "Zaza": ["Gashanda", "Jarama", "Karembo", "Zaza", "Kibungo"]},
        "Nyagatare": {"Gatunda": ["Gatunda", "Karama", "Karangazi", "Katabagemu", "Kayonza"], "Karama": ["Gatunda", "Karama", "Karangazi", "Katabagemu", "Kayonza"], "Karangazi": ["Gatunda", "Karama", "Karangazi", "Katabagemu", "Kayonza"], "Katabagemu": ["Gatunda", "Karama", "Karangazi", "Katabagemu", "Kayonza"], "Kayonza": ["Gatunda", "Karama", "Karangazi", "Katabagemu", "Kayonza"], "Mimuli": ["Gatunda", "Karama", "Karangazi", "Mimuli", "Kayonza"], "Mukama": ["Gatunda", "Karama", "Karangazi", "Mukama", "Kayonza"], "Musheli": ["Gatunda", "Karama", "Karangazi", "Musheli", "Kayonza"], "Nyagatare": ["Gatunda", "Karama", "Karangazi", "Nyagatare", "Kayonza"], "Nyagihanga": ["Gatunda", "Karama", "Karangazi", "Nyagihanga", "Kayonza"], "Rukomo": ["Gatunda", "Karama", "Karangazi", "Rukomo", "Kayonza"], "Rwempasha": ["Gatunda", "Karama", "Karangazi", "Rwempasha", "Kayonza"], "Rwimiyaga": ["Gatunda", "Karama", "Karangazi", "Rwimiyaga", "Kayonza"], "Tabagwe": ["Gatunda", "Karama", "Karangazi", "Tabagwe", "Kayonza"]},
        "Rwamagana": {"Fumbwe": ["Fumbwe", "Gahengeri", "Gishari", "Karenge", "Kigabiro"], "Gahengeri": ["Fumbwe", "Gahengeri", "Gishari", "Karenge", "Kigabiro"], "Gishari": ["Fumbwe", "Gahengeri", "Gishari", "Karenge", "Kigabiro"], "Karenge": ["Fumbwe", "Gahengeri", "Gishari", "Karenge", "Kigabiro"], "Kigabiro": ["Fumbwe", "Gahengeri", "Gishari", "Karenge", "Kigabiro"], "Muhazi": ["Fumbwe", "Gahengeri", "Gishari", "Muhazi", "Kigabiro"], "Munyaga": ["Fumbwe", "Gahengeri", "Gishari", "Munyaga", "Kigabiro"], "Munyiginya": ["Fumbwe", "Gahengeri", "Gishari", "Munyiginya", "Kigabiro"], "Musha": ["Fumbwe", "Gahengeri", "Gishari", "Musha", "Kigabiro"], "Muyumbu": ["Fumbwe", "Gahengeri", "Gishari", "Muyumbu", "Kigabiro"], "Mwulire": ["Fumbwe", "Gahengeri", "Gishari", "Mwulire", "Kigabiro"], "Nyakariro": ["Fumbwe", "Gahengeri", "Gishari", "Nyakariro", "Kigabiro"], "Nzige": ["Fumbwe", "Gahengeri", "Gishari", "Nzige", "Kigabiro"], "Rubona": ["Fumbwe", "Gahengeri", "Gishari", "Rubona", "Kigabiro"]},
    },
    "Western": {
        "Karongi":    {"Bwishyura": ["Bwishyura", "Gishyita", "Gitesi", "Mubuga", "Murambi"], "Gishyita": ["Bwishyura", "Gishyita", "Gitesi", "Mubuga", "Murambi"], "Gitesi": ["Bwishyura", "Gishyita", "Gitesi", "Mubuga", "Murambi"], "Mubuga": ["Bwishyura", "Gishyita", "Gitesi", "Mubuga", "Murambi"], "Murambi": ["Bwishyura", "Gishyita", "Gitesi", "Mubuga", "Murambi"], "Mutuntu": ["Bwishyura", "Gishyita", "Gitesi", "Mutuntu", "Murambi"], "Rubengera": ["Bwishyura", "Gishyita", "Gitesi", "Rubengera", "Murambi"], "Rugabano": ["Bwishyura", "Gishyita", "Gitesi", "Rugabano", "Murambi"], "Ruganda": ["Bwishyura", "Gishyita", "Gitesi", "Ruganda", "Murambi"], "Rwankuba": ["Bwishyura", "Gishyita", "Gitesi", "Rwankuba", "Murambi"], "Twumba": ["Bwishyura", "Gishyita", "Gitesi", "Twumba", "Murambi"]},
        "Ngororero":  {"Bwira": ["Bwira", "Gatumba", "Hindiro", "Kabaya", "Kagabiro"], "Gatumba": ["Bwira", "Gatumba", "Hindiro", "Kabaya", "Kagabiro"], "Hindiro": ["Bwira", "Gatumba", "Hindiro", "Kabaya", "Kagabiro"], "Kabaya": ["Bwira", "Gatumba", "Hindiro", "Kabaya", "Kagabiro"], "Kagabiro": ["Bwira", "Gatumba", "Hindiro", "Kabaya", "Kagabiro"], "Kavumu": ["Bwira", "Gatumba", "Hindiro", "Kavumu", "Kagabiro"], "Matyazo": ["Bwira", "Gatumba", "Hindiro", "Matyazo", "Kagabiro"], "Muhanda": ["Bwira", "Gatumba", "Hindiro", "Muhanda", "Kagabiro"], "Muhororo": ["Bwira", "Gatumba", "Hindiro", "Muhororo", "Kagabiro"], "Ndaro": ["Bwira", "Gatumba", "Hindiro", "Ndaro", "Kagabiro"], "Ngororero": ["Bwira", "Gatumba", "Hindiro", "Ngororero", "Kagabiro"], "Nyange": ["Bwira", "Gatumba", "Hindiro", "Nyange", "Kagabiro"], "Sovu": ["Bwira", "Gatumba", "Hindiro", "Sovu", "Kagabiro"]},
        "Nyabihu":    {"Bigogwe": ["Bigogwe", "Jenda", "Jomba", "Kabatwa", "Karago"], "Jenda": ["Bigogwe", "Jenda", "Jomba", "Kabatwa", "Karago"], "Jomba": ["Bigogwe", "Jenda", "Jomba", "Kabatwa", "Karago"], "Kabatwa": ["Bigogwe", "Jenda", "Jomba", "Kabatwa", "Karago"], "Karago": ["Bigogwe", "Jenda", "Jomba", "Kabatwa", "Karago"], "Kintobo": ["Bigogwe", "Jenda", "Jomba", "Kintobo", "Karago"], "Mukamira": ["Bigogwe", "Jenda", "Jomba", "Mukamira", "Karago"], "Muringa": ["Bigogwe", "Jenda", "Jomba", "Muringa", "Karago"], "Rambura": ["Bigogwe", "Jenda", "Jomba", "Rambura", "Karago"], "Rugera": ["Bigogwe", "Jenda", "Jomba", "Rugera", "Karago"], "Rurembo": ["Bigogwe", "Jenda", "Jomba", "Rurembo", "Karago"], "Shyira": ["Bigogwe", "Jenda", "Jomba", "Shyira", "Karago"]},
        "Nyamasheke": {"Bushekeri": ["Bushekeri", "Bushenge", "Cyato", "Gihombo", "Kagano"], "Bushenge": ["Bushekeri", "Bushenge", "Cyato", "Gihombo", "Kagano"], "Cyato": ["Bushekeri", "Bushenge", "Cyato", "Gihombo", "Kagano"], "Gihombo": ["Bushekeri", "Bushenge", "Cyato", "Gihombo", "Kagano"], "Kagano": ["Bushekeri", "Bushenge", "Cyato", "Gihombo", "Kagano"], "Kanjongo": ["Bushekeri", "Bushenge", "Cyato", "Kanjongo", "Kagano"], "Karambi": ["Bushekeri", "Bushenge", "Cyato", "Karambi", "Kagano"], "Karengera": ["Bushekeri", "Bushenge", "Cyato", "Karengera", "Kagano"], "Kirimbi": ["Bushekeri", "Bushenge", "Cyato", "Kirimbi", "Kagano"], "Macuba": ["Bushekeri", "Bushenge", "Cyato", "Macuba", "Kagano"], "Mahembe": ["Bushekeri", "Bushenge", "Cyato", "Mahembe", "Kagano"], "Nyabitekeri": ["Bushekeri", "Bushenge", "Cyato", "Nyabitekeri", "Kagano"], "Rangiro": ["Bushekeri", "Bushenge", "Cyato", "Rangiro", "Kagano"], "Ruharambuga": ["Bushekeri", "Bushenge", "Cyato", "Ruharambuga", "Kagano"], "Shangi": ["Bushekeri", "Bushenge", "Cyato", "Shangi", "Kagano"]},
        "Rubavu":     {"Bugeshi": ["Bugeshi", "Busasamana", "Cyanzarwe", "Gisenyi", "Kanama"], "Busasamana": ["Bugeshi", "Busasamana", "Cyanzarwe", "Gisenyi", "Kanama"], "Cyanzarwe": ["Bugeshi", "Busasamana", "Cyanzarwe", "Gisenyi", "Kanama"], "Gisenyi": ["Bugeshi", "Busasamana", "Cyanzarwe", "Gisenyi", "Kanama"], "Kanama": ["Bugeshi", "Busasamana", "Cyanzarwe", "Gisenyi", "Kanama"], "Kanzenze": ["Bugeshi", "Busasamana", "Cyanzarwe", "Kanzenze", "Kanama"], "Mudende": ["Bugeshi", "Busasamana", "Cyanzarwe", "Mudende", "Kanama"], "Nyamyumba": ["Bugeshi", "Busasamana", "Cyanzarwe", "Nyamyumba", "Kanama"], "Nyundo": ["Bugeshi", "Busasamana", "Cyanzarwe", "Nyundo", "Kanama"], "Rubavu": ["Bugeshi", "Busasamana", "Cyanzarwe", "Rubavu", "Kanama"], "Rugerero": ["Bugeshi", "Busasamana", "Cyanzarwe", "Rugerero", "Kanama"]},
        "Rutsiro":    {"Boneza": ["Boneza", "Gihango", "Kigeyo", "Kivumu", "Manishya"], "Gihango": ["Boneza", "Gihango", "Kigeyo", "Kivumu", "Manishya"], "Kigeyo": ["Boneza", "Gihango", "Kigeyo", "Kivumu", "Manishya"], "Kivumu": ["Boneza", "Gihango", "Kigeyo", "Kivumu", "Manishya"], "Manishya": ["Boneza", "Gihango", "Kigeyo", "Kivumu", "Manishya"], "Mbogo": ["Boneza", "Gihango", "Kigeyo", "Mbogo", "Manishya"], "Mushonyi": ["Boneza", "Gihango", "Kigeyo", "Mushonyi", "Manishya"], "Mushubati": ["Boneza", "Gihango", "Kigeyo", "Mushubati", "Manishya"], "Nyabirasi": ["Boneza", "Gihango", "Kigeyo", "Nyabirasi", "Manishya"], "Ruhango": ["Boneza", "Gihango", "Kigeyo", "Ruhango", "Manishya"], "Rusebeya": ["Boneza", "Gihango", "Kigeyo", "Rusebeya", "Manishya"]},
        "Rusizi":     {"Bugarama": ["Bugarama", "Butare", "Bweyeye", "Gashonga", "Giheke"], "Butare": ["Bugarama", "Butare", "Bweyeye", "Gashonga", "Giheke"], "Bweyeye": ["Bugarama", "Butare", "Bweyeye", "Gashonga", "Giheke"], "Gashonga": ["Bugarama", "Butare", "Bweyeye", "Gashonga", "Giheke"], "Giheke": ["Bugarama", "Butare", "Bweyeye", "Gashonga", "Giheke"], "Gihundwe": ["Bugarama", "Butare", "Bweyeye", "Gihundwe", "Giheke"], "Gitambi": ["Bugarama", "Butare", "Bweyeye", "Gitambi", "Giheke"], "Kamembe": ["Bugarama", "Butare", "Bweyeye", "Kamembe", "Giheke"], "Muganza": ["Bugarama", "Butare", "Bweyeye", "Muganza", "Giheke"], "Mururu": ["Bugarama", "Butare", "Bweyeye", "Mururu", "Giheke"], "Nkanka": ["Bugarama", "Butare", "Bweyeye", "Nkanka", "Giheke"], "Nkungu": ["Bugarama", "Butare", "Bweyeye", "Nkungu", "Giheke"], "Nyakabuye": ["Bugarama", "Butare", "Bweyeye", "Nyakabuye", "Giheke"], "Nyakarenzo": ["Bugarama", "Butare", "Bweyeye", "Nyakarenzo", "Giheke"], "Nzahaha": ["Bugarama", "Butare", "Bweyeye", "Nzahaha", "Giheke"], "Rwimbogo": ["Bugarama", "Butare", "Bweyeye", "Rwimbogo", "Giheke"]},
    },
}


def get_provinces():
    return list(RWANDA_LOCATIONS.keys())


def get_districts(province):
    return list(RWANDA_LOCATIONS.get(province, {}).keys())


def get_sectors(province, district):
    return list(RWANDA_LOCATIONS.get(province, {}).get(district, {}).keys())


def get_cells(province, district, sector):
    sectors = RWANDA_LOCATIONS.get(province, {}).get(district, {})
    return sectors.get(sector, [])