# Generated by Django 5.1.3 on 2026-03-08 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0003_alter_meter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meter',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disabled', 'Disabled')], default='active', max_length=10),
        ),
    ]
