# Generated by Django 5.1.3 on 2026-03-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0004_alter_meter_low_balance_threshold_alter_meter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='device_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
