# Generated by Django 5.1.3 on 2026-03-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0006_meter_cell_meter_district_meter_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='meter_name',
            field=models.CharField(blank=True, default='My Meter', max_length=100),
        ),
    ]
