# Generated by Django 5.1.3 on 2026-03-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0007_meter_meter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='meter_name',
        ),
        migrations.AddField(
            model_name='meterrequest',
            name='meter_name',
            field=models.CharField(blank=True, default='My Meter', max_length=100),
        ),
    ]
