# Generated by Django 5.1.3 on 2026-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0008_remove_meter_meter_name_meterrequest_meter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential (Household)'), ('non_residential', 'Non-Residential'), ('health', 'Health Facility'), ('school', 'School / Higher Learning Institution'), ('hotel_small', 'Hotel (annual consumption < 660,000 kWh)'), ('hotel_large', 'Hotel (annual consumption >= 660,000 kWh)'), ('commercial', 'Commercial / Data Centre'), ('water_pumping', 'Water Pumping Station'), ('water_treatment', 'Water Treatment Plant'), ('telecom', 'Telecom Tower'), ('industry_small', 'Industry - Small (5,000-100,000 kWh/yr)'), ('industry_medium', 'Industry - Medium (100,000-1,000,000 kWh/yr)'), ('industry_large', 'Industry - Large (>=1,000,000 kWh/yr)')], default='residential', help_text='REG tariff category — determines price per kWh', max_length=30),
        ),
        migrations.AddField(
            model_name='meterrequest',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential (Household)'), ('non_residential', 'Non-Residential'), ('health', 'Health Facility'), ('school', 'School / Higher Learning Institution'), ('hotel_small', 'Hotel (annual consumption < 660,000 kWh)'), ('hotel_large', 'Hotel (annual consumption >= 660,000 kWh)'), ('commercial', 'Commercial / Data Centre'), ('water_pumping', 'Water Pumping Station'), ('water_treatment', 'Water Treatment Plant'), ('telecom', 'Telecom Tower'), ('industry_small', 'Industry - Small (5,000-100,000 kWh/yr)'), ('industry_medium', 'Industry - Medium (100,000-1,000,000 kWh/yr)'), ('industry_large', 'Industry - Large (>=1,000,000 kWh/yr)')], default='residential', help_text='REG tariff category', max_length=30),
        ),
    ]
